apiVersion: batch/v1
kind: Job
metadata:
  name: resource-adaptor-migration
spec:
  template:
    metadata:
      name: resource-adaptor-migration
    spec:
      containers:
      - name: resource-adaptor-migration
        image: arthurmde/resource-adaptor:0.2-0.3-exp2
        env:
          - name: POSTGRES_USER
            value: stolon
          - name: POSTGRES_PASSWORD
            value: interscity
          - name: POSTGRES_HOST
            value: stolon-proxy-service
          - name: POSTGRES_PORT
            value: '5432'
          - name: RABBITMQ_HOST
            value: 'rabbitmq'
          - name: KONG_URI
            value: 'http://kong-admin:8001'
          - name: REGISTER_METHOD
            value: 'target'
        command: [ "/bin/sh", "-c", "rake db:create && rake db:migrate" ]
      restartPolicy: Never
